# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     Robert-Zacchigna/BlackDoc

# Setup
title:            hroe.me
tagline:          Henry Roe's spot on these interwebs
description:      "A spot for<br>Henry Roe's<br>professional, personal, and other interests"
url:              https://henryroe.github.io
baseurl:          "/"
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

timezone: America/Santiago

author:
  name:           Henry Roe
  url:            https://github.com/henryroe/

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.0

github:
  repo:             https://github.com/henryroe/henryroe.github.io

